Use to Material Alert Dialog
meenbeese/Chronos pull request #46
Opened 2024-04-12 19:05 UTC by Jean-BaptisteC

This PR:
- Remove the custom implementation of AlertDialog
- Use native Material Alert Dialog

2024-04-12 22:57 UTC, meenbeese requested changes
Thanks for helping with this migration. I like the changes but the dialog color in light mode is wrong, can you fix it? 
</br>
![Screenshot 2024-04-12 185323](https://github.com/meenbeese/Chronos/assets/114044633/53d07703-e5dd-435f-8da9-dc939d811938)

2024-04-13 10:34 UTC, Jean-BaptisteC commented
I have done a correction, but we don't have a dialog theme for AMOLED theme

2024-04-13 17:22 UTC, meenbeese commented on app/src/main/java/com/meenbeese/chronos/Chronos.kt
> +    fun isDarkTheme():Boolean {
```suggestion
    fun isDarkTheme(): Boolean {
```

2024-04-13 22:26 UTC, meenbeese commented
> I have done a correction, but we don't have a dialog theme for AMOLED theme

Thanks, that is not a huge concern. I need to rework the entire theme handling in the future anyway.

2024-04-13 22:26 UTC, merged